### ISSUE TITLE
Would it be convenient for you to provide a copy of the mesh model

### ISSUE THREAD

**Issue by ZhouWeikun** [wyc-Chang/ImMPI#2]
Thanks for your nice work.  And I want to follow your work. But I can't find the mesh model in the dataset you shared.  Would it be convenient for you to provide a copy of the mesh model?

**Comment by SunshineWYC** [comment]
Sry, this dataset is mainly aimming at novel view synthesis task which supplies multi-view images and corresponding poses. The mesh model is not convenient to publish due to copyright issues. If you indeed need mesh model of each scene, you can try mesh reconstruction methods like COLMAP to get a replacement.

**Comment by ZhouWeikun** [comment]
Okay, thank you. I'll try to think of something else.
